spring:
  datasource:
    url: jdbc:postgresql://testingdb.cjqm4aimakm9.ap-south-1.rds.amazonaws.com:5432/postgres
    username: bharatteleclinic
    password: Blat786YUnUs!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jwt:
    secret: ${JWT_SECRET:defaultsecretkeydefaultsecretkey}
    expiration: 3600000 

  servlet:
      multipart:
        max-file-size: 50MB      
        max-request-size: 100MB   
  http:
    multipart:
      enabled: true
    
      
server:
  address: 0.0.0.0
  port: 8080  

  tomcat:
    max-swallow-size: 100MB     